export type RouteAvailability = 'implemented' | 'prototype' | 'unavailable';
export type RouteAudience = 'public' | 'student' | 'parent-preview' | 'account';
export type RouteAccess =
  | 'public'
  | 'unsupported'
  | 'role-selection'
  | 'parent-onboarding'
  | 'parent-preview'
  | 'commerce-preview'
  | 'preview-context'
  | 'production-auth'
  | 'student-onboarding-preview'
  | 'student-workspace-preview';

export type NavigationPlacement = 'primary' | 'secondary' | 'hidden';
export type MobileNavigationPlacement = 'primary' | 'more' | 'hidden';

export interface AppRouteDefinition {
  id: string;
  path: string;
  labelKey: string;
  availability: RouteAvailability;
  access: RouteAccess;
  audience: RouteAudience;
  navigation: NavigationPlacement;
  mobileNavigation?: MobileNavigationPlacement;
  requirementAreas: string[];
  activePaths?: readonly RouteActivePath[];
  prototypeOnly?: boolean;
}

export interface RouteActivePath {
  path: string;
  exact?: boolean;
}

function defineRoutes<const T extends readonly AppRouteDefinition[]>(routes: T): T {
  return routes;
}

export const routeManifest = defineRoutes([
  // Public site and account entry
  route(
    'home',
    '/',
    'public.nav.home',
    'prototype',
    'public',
    'public',
    'primary',
    ['0.1'],
    true,
    undefined,
    [{ path: '/', exact: true }],
  ),
  route(
    'products',
    '/products',
    'public.nav.products',
    'prototype',
    'public',
    'public',
    'primary',
    ['11.1'],
    true,
  ),
  route(
    'product-detail',
    '/products/:productId',
    'public.nav.products',
    'prototype',
    'public',
    'public',
    'hidden',
    ['11.1'],
    true,
  ),
  route(
    'trial',
    '/trial',
    'public.nav.trial',
    'prototype',
    'public',
    'public',
    'primary',
    ['11.2'],
    true,
  ),
  route(
    'for-parents',
    '/for-parents',
    'public.nav.forParents',
    'prototype',
    'public',
    'public',
    'primary',
    ['10.1'],
    true,
  ),
  route(
    'privacy',
    '/privacy',
    'public.footer.privacy',
    'prototype',
    'public',
    'public',
    'hidden',
    ['12.1'],
    true,
  ),
  route(
    'terms',
    '/terms',
    'public.footer.terms',
    'prototype',
    'public',
    'public',
    'hidden',
    ['12.1'],
    true,
  ),
  route(
    'register',
    '/register',
    'public.nav.createAccount',
    'implemented',
    'public',
    'public',
    'hidden',
    ['1.1'],
  ),
  route('login', '/login', 'nav.login', 'implemented', 'public', 'public', 'hidden', ['1.1']),
  route(
    'verify-email',
    '/verify-email',
    'public.nav.createAccount',
    'implemented',
    'public',
    'public',
    'hidden',
    ['1.1'],
  ),
  route(
    'forgot-password',
    '/forgot-password',
    'nav.login',
    'implemented',
    'public',
    'public',
    'hidden',
    ['1.1'],
  ),
  route(
    'reset-password',
    '/reset-password',
    'nav.login',
    'implemented',
    'public',
    'public',
    'hidden',
    ['1.1'],
  ),
  route(
    'credential-login',
    '/credential-login',
    'nav.login',
    'implemented',
    'public',
    'public',
    'hidden',
    ['1.1'],
  ),
  route(
    'unsupported',
    '/unsupported',
    'nav.login',
    'implemented',
    'unsupported',
    'account',
    'hidden',
    ['1.1'],
  ),

  // Role and profile activation
  route(
    'role-selection',
    '/onboarding/role',
    'role.title',
    'prototype',
    'role-selection',
    'account',
    'hidden',
    ['1.2', '1.3'],
    true,
  ),
  route(
    'parent-onboarding',
    '/onboarding/parent',
    'parent.nav.home',
    'prototype',
    'parent-onboarding',
    'parent-preview',
    'hidden',
    ['1.3'],
    true,
  ),
  route(
    'student-activation',
    '/onboarding/student',
    'nav.activation',
    'implemented',
    'production-auth',
    'student',
    'hidden',
    ['1.2'],
  ),

  // Parent preview workspace
  route(
    'parent-home',
    '/parent/home',
    'parent.nav.home',
    'prototype',
    'parent-preview',
    'parent-preview',
    'primary',
    ['10.1'],
    true,
    'primary',
    [{ path: '/parent/home', exact: true }],
  ),
  route(
    'parent-family',
    '/parent/family',
    'parent.nav.family',
    'prototype',
    'parent-preview',
    'parent-preview',
    'primary',
    ['2.1', '2.2'],
    true,
    'primary',
    [{ path: '/parent/family' }, { path: '/parent/invitations' }],
  ),
  route(
    'parent-family-create-student',
    '/parent/family/create-student',
    'parent.nav.family',
    'prototype',
    'parent-preview',
    'parent-preview',
    'hidden',
    ['2.1'],
    true,
  ),
  route(
    'parent-invitation',
    '/parent/invitations/:invitationId',
    'parent.nav.family',
    'prototype',
    'parent-preview',
    'parent-preview',
    'hidden',
    ['2.2'],
    true,
  ),
  route(
    'parent-reports',
    '/parent/reports',
    'parent.nav.reports',
    'prototype',
    'parent-preview',
    'parent-preview',
    'primary',
    ['10.2'],
    true,
    'primary',
    [{ path: '/parent/reports' }, { path: '/parent/students' }],
  ),
  route(
    'parent-student',
    '/parent/students/:studentId',
    'parent.nav.reports',
    'prototype',
    'parent-preview',
    'parent-preview',
    'hidden',
    ['10.1'],
    true,
  ),
  route(
    'parent-student-report',
    '/parent/students/:studentId/report',
    'parent.nav.reports',
    'prototype',
    'parent-preview',
    'parent-preview',
    'hidden',
    ['10.2'],
    true,
  ),
  route(
    'parent-purchases',
    '/parent/purchases',
    'parent.nav.purchases',
    'prototype',
    'parent-preview',
    'parent-preview',
    'primary',
    ['11.3'],
    true,
    'primary',
    [{ path: '/parent/purchases' }, { path: '/parent/orders' }],
  ),
  route(
    'parent-orders',
    '/parent/orders',
    'commerce.orders.title',
    'prototype',
    'parent-preview',
    'parent-preview',
    'hidden',
    ['11.5'],
    true,
  ),
  route(
    'parent-order-detail',
    '/parent/orders/:orderId',
    'commerce.orders.title',
    'prototype',
    'parent-preview',
    'parent-preview',
    'hidden',
    ['11.5'],
    true,
  ),
  route(
    'parent-account',
    '/parent/account',
    'parent.nav.account',
    'prototype',
    'parent-preview',
    'parent-preview',
    'primary',
    ['1.3'],
    true,
    'primary',
    [{ path: '/parent/account' }, { path: '/parent/support' }],
  ),
  route(
    'parent-notifications',
    '/parent/account/notifications',
    'parent.nav.account',
    'prototype',
    'parent-preview',
    'parent-preview',
    'hidden',
    ['13.1'],
    true,
  ),
  route(
    'parent-account-privacy',
    '/parent/account/privacy',
    'parent.nav.account',
    'prototype',
    'parent-preview',
    'parent-preview',
    'hidden',
    ['12.1'],
    true,
  ),
  route(
    'parent-support',
    '/parent/support',
    'support.title',
    'prototype',
    'parent-preview',
    'parent-preview',
    'hidden',
    ['13.2'],
    true,
  ),

  // Commerce, aftercare, account, and support previews
  route(
    'checkout',
    '/checkout',
    'commerce.checkout.title',
    'prototype',
    'commerce-preview',
    'account',
    'hidden',
    ['11.3'],
    true,
  ),
  route(
    'checkout-payment',
    '/checkout/payment',
    'commerce.checkout.title',
    'prototype',
    'commerce-preview',
    'account',
    'hidden',
    ['11.3'],
    true,
  ),
  route(
    'checkout-instructions',
    '/checkout/instructions',
    'commerce.checkout.title',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['11.3'],
    true,
  ),
  route(
    'orders',
    '/orders',
    'commerce.orders.title',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['11.5'],
    true,
  ),
  route(
    'order-detail',
    '/orders/:orderId',
    'commerce.orders.title',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['11.5'],
    true,
  ),
  route(
    'order-refund',
    '/orders/:orderId/refund',
    'commerce.orders.title',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['11.6'],
    true,
  ),
  route(
    'entitlements',
    '/entitlements',
    'parent.nav.purchases',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['11.4'],
    true,
  ),
  route(
    'entitlement-renew',
    '/entitlements/:entitlementId/renew',
    'parent.nav.purchases',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['11.7'],
    true,
  ),
  route(
    'account-notifications',
    '/account/notifications',
    'parent.nav.account',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['13.1'],
    true,
  ),
  route(
    'account-privacy',
    '/account/privacy',
    'parent.nav.account',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['12.1'],
    true,
  ),
  route(
    'account-export',
    '/account/export',
    'parent.nav.account',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['12.2'],
    true,
  ),
  route(
    'account-delete',
    '/account/delete',
    'parent.nav.account',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['12.2'],
    true,
  ),
  route(
    'support',
    '/support',
    'support.title',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['13.2'],
    true,
  ),
  route(
    'support-new',
    '/support/new',
    'support.title',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['13.2'],
    true,
  ),
  route(
    'support-ticket',
    '/support/:ticketId',
    'support.title',
    'prototype',
    'preview-context',
    'account',
    'hidden',
    ['13.2'],
    true,
  ),

  // Student onboarding preview
  route(
    'onboarding-goals',
    '/onboarding/student/goals',
    'nav.goals',
    'prototype',
    'student-onboarding-preview',
    'student',
    'hidden',
    ['3.1'],
    true,
  ),
  route(
    'onboarding-subjects',
    '/onboarding/student/subjects',
    'nav.subjects',
    'prototype',
    'student-onboarding-preview',
    'student',
    'hidden',
    ['3.2', '3.3'],
    true,
  ),
  route(
    'onboarding-diagnostic',
    '/onboarding/student/diagnostic',
    'nav.diagnostic',
    'prototype',
    'student-onboarding-preview',
    'student',
    'hidden',
    ['3.4'],
    true,
  ),
  route(
    'onboarding-diagnostic-result',
    '/onboarding/student/diagnostic/result',
    'nav.diagnosticResult',
    'prototype',
    'student-onboarding-preview',
    'student',
    'hidden',
    ['3.4'],
    true,
  ),
  route(
    'onboarding-plan-review',
    '/onboarding/student/plan-review',
    'nav.planReview',
    'prototype',
    'student-onboarding-preview',
    'student',
    'hidden',
    ['3.4', '3.5'],
    true,
  ),

  // Student workspace
  route(
    'today',
    '/app/today',
    'nav.today',
    'prototype',
    'student-workspace-preview',
    'student',
    'primary',
    ['6.1', '6.2', '6.3', '8.1'],
    true,
    'primary',
  ),
  route(
    'learn',
    '/app/learn',
    'nav.learn',
    'prototype',
    'student-workspace-preview',
    'student',
    'primary',
    ['4.1', '4.3', '4.4'],
    true,
    'primary',
  ),
  route(
    'learn-syllabus',
    '/app/learn/syllabus',
    'nav.syllabus',
    'prototype',
    'student-workspace-preview',
    'student',
    'hidden',
    ['4.2'],
    true,
  ),
  route(
    'learn-lesson',
    '/app/learn/:lessonId',
    'nav.lesson',
    'prototype',
    'student-workspace-preview',
    'student',
    'hidden',
    ['4.4', '4.5', '4.6'],
    true,
  ),
  route(
    'practice',
    '/app/practice',
    'nav.practice',
    'prototype',
    'student-workspace-preview',
    'student',
    'primary',
    ['5.1', '5.2'],
    true,
    'primary',
  ),
  route(
    'practice-session',
    '/app/practice/:sessionId',
    'nav.practiceSession',
    'prototype',
    'student-workspace-preview',
    'student',
    'hidden',
    ['5.1', '5.2', '5.3'],
    true,
  ),
  route(
    'practice-result',
    '/app/practice/:sessionId/result',
    'nav.practiceResult',
    'prototype',
    'student-workspace-preview',
    'student',
    'hidden',
    ['5.3', '5.4'],
    true,
  ),
  route(
    'practice-mistakes',
    '/app/practice/mistakes',
    'nav.mistakes',
    'prototype',
    'student-workspace-preview',
    'student',
    'hidden',
    ['5.4'],
    true,
  ),
  route(
    'practice-mistake-detail',
    '/app/practice/mistakes/:mistakeId',
    'nav.mistakeDetail',
    'prototype',
    'student-workspace-preview',
    'student',
    'hidden',
    ['5.4', '6.4'],
    true,
  ),
  route(
    'mock-exams',
    '/app/mock-exams',
    'nav.mockExams',
    'prototype',
    'student-workspace-preview',
    'student',
    'primary',
    ['7.1'],
    true,
    'more',
  ),
  route(
    'mock-instructions',
    '/app/mock-exams/:examId/instructions',
    'nav.mockInstructions',
    'prototype',
    'student-workspace-preview',
    'student',
    'hidden',
    ['7.1', '7.2'],
    true,
  ),
  route(
    'mock-session',
    '/app/mock-exams/:examId/session',
    'nav.mockSession',
    'prototype',
    'student-workspace-preview',
    'student',
    'hidden',
    ['7.2', '7.3'],
    true,
  ),
  route(
    'mock-result',
    '/app/mock-exams/:examId/result',
    'nav.mockResult',
    'prototype',
    'student-workspace-preview',
    'student',
    'hidden',
    ['7.4'],
    true,
  ),
  route(
    'progress',
    '/app/progress',
    'nav.progress',
    'prototype',
    'student-workspace-preview',
    'student',
    'primary',
    ['8.1', '8.3'],
    true,
    'primary',
  ),
  route(
    'profile',
    '/app/profile',
    'nav.profile',
    'implemented',
    'student-workspace-preview',
    'student',
    'primary',
    ['1.3', '1.4'],
    false,
    'more',
  ),
  route(
    'profile-languages',
    '/app/profile/languages',
    'nav.languages',
    'prototype',
    'student-workspace-preview',
    'student',
    'secondary',
    ['1.4'],
    true,
    'more',
  ),
  route(
    'profile-family',
    '/app/profile/family',
    'nav.family',
    'prototype',
    'student-workspace-preview',
    'student',
    'secondary',
    ['2.2', '2.3'],
    true,
    'more',
  ),
  route(
    'profile-access',
    '/app/profile/access',
    'nav.access',
    'prototype',
    'student-workspace-preview',
    'student',
    'secondary',
    ['11.1', '11.2'],
    true,
    'more',
  ),
  route(
    'more',
    '/app/more',
    'nav.more',
    'implemented',
    'student-workspace-preview',
    'student',
    'hidden',
    [],
    false,
    'primary',
  ),
] as const);

export type RouteId = (typeof routeManifest)[number]['id'];

export const primaryNavRoutes = routeManifest.filter(
  (route) => route.navigation === 'primary' && route.audience === 'student',
);
export const mobilePrimaryNavRoutes = routeManifest.filter(
  (route) => route.mobileNavigation === 'primary' && route.audience === 'student',
);
export const mobileMoreRoutes = routeManifest.filter(
  (route) => route.mobileNavigation === 'more' && route.audience === 'student',
);
export const parentNavRoutes = routeManifest.filter(
  (route) => route.navigation === 'primary' && route.audience === 'parent-preview',
);
export const parentMobileNavRoutes = routeManifest.filter(
  (route) => route.mobileNavigation === 'primary' && route.audience === 'parent-preview',
);
export const publicNavRoutes = routeManifest.filter(
  (route) => route.navigation === 'primary' && route.audience === 'public',
);

export function routesForAccess(access: RouteAccess) {
  return routeManifest.filter((route) => route.access === access);
}

export function getRouteById(id: RouteId): AppRouteDefinition {
  const found = routeManifest.find((route) => route.id === id);
  if (!found) {
    throw new Error(`Unknown route id: ${id}`);
  }
  return found;
}

export function isRouteActive(route: AppRouteDefinition, pathname: string): boolean {
  const activePaths = route.activePaths ?? [{ path: route.path }];
  return activePaths.some((activePath) =>
    activePath.exact ? pathname === activePath.path : pathname.startsWith(activePath.path),
  );
}

function route<const I extends string, const A extends RouteAccess>(
  id: I,
  path: string,
  labelKey: string,
  availability: RouteAvailability,
  access: A,
  audience: RouteAudience,
  navigation: NavigationPlacement,
  requirementAreas: string[],
  prototypeOnly = false,
  mobileNavigation?: MobileNavigationPlacement,
  activePaths?: readonly RouteActivePath[],
): AppRouteDefinition & { readonly id: I; readonly access: A } {
  return {
    id,
    path,
    labelKey,
    availability,
    access,
    audience,
    navigation,
    ...(mobileNavigation ? { mobileNavigation } : {}),
    requirementAreas,
    ...(activePaths ? { activePaths } : {}),
    ...(prototypeOnly ? { prototypeOnly: true } : {}),
  };
}
