import type { UserRole } from '@/features/auth/auth.types';

export type RouteAvailability = 'implemented' | 'prototype' | 'unavailable';

export type NavigationPlacement = 'primary' | 'secondary' | 'hidden';
export type MobileNavigationPlacement = 'primary' | 'more' | 'hidden';

export interface AppRouteDefinition {
  id: string;
  path: string;
  labelKey: string;
  availability: RouteAvailability;
  allowedRoles: UserRole[];
  navigation: NavigationPlacement;
  mobileNavigation?: MobileNavigationPlacement;
  requirementAreas: string[];
  prototypeOnly?: boolean;
}

const STUDENT: UserRole[] = ['STUDENT'];

export const routeManifest: AppRouteDefinition[] = [
  {
    id: 'login',
    path: '/login',
    labelKey: 'nav.login',
    availability: 'implemented',
    allowedRoles: ['UNASSIGNED', 'STUDENT', 'PARENT', 'TUTOR', 'ADMIN'],
    navigation: 'hidden',
    requirementAreas: ['1.1'],
  },
  {
    id: 'student-activation',
    path: '/onboarding/student',
    labelKey: 'nav.activation',
    availability: 'implemented',
    allowedRoles: ['UNASSIGNED'],
    navigation: 'hidden',
    requirementAreas: ['1.2'],
  },
  {
    id: 'onboarding-goals',
    path: '/onboarding/student/goals',
    labelKey: 'nav.goals',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['3.1'],
    prototypeOnly: true,
  },
  {
    id: 'onboarding-subjects',
    path: '/onboarding/student/subjects',
    labelKey: 'nav.subjects',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['3.2', '3.3'],
    prototypeOnly: true,
  },
  {
    id: 'onboarding-diagnostic',
    path: '/onboarding/student/diagnostic',
    labelKey: 'nav.diagnostic',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['3.4'],
    prototypeOnly: true,
  },
  {
    id: 'onboarding-diagnostic-result',
    path: '/onboarding/student/diagnostic/result',
    labelKey: 'nav.diagnosticResult',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['3.4'],
    prototypeOnly: true,
  },
  {
    id: 'onboarding-plan-review',
    path: '/onboarding/student/plan-review',
    labelKey: 'nav.planReview',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['3.4', '3.5'],
    prototypeOnly: true,
  },
  {
    id: 'today',
    path: '/app/today',
    labelKey: 'nav.today',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'primary',
    mobileNavigation: 'primary',
    requirementAreas: ['6.1', '6.2', '6.3', '8.1'],
    prototypeOnly: true,
  },
  {
    id: 'learn',
    path: '/app/learn',
    labelKey: 'nav.learn',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'primary',
    mobileNavigation: 'primary',
    requirementAreas: ['4.1', '4.3', '4.4'],
    prototypeOnly: true,
  },
  {
    id: 'learn-syllabus',
    path: '/app/learn/syllabus',
    labelKey: 'nav.syllabus',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['4.2'],
    prototypeOnly: true,
  },
  {
    id: 'learn-lesson',
    path: '/app/learn/:lessonId',
    labelKey: 'nav.lesson',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['4.4', '4.5', '4.6'],
    prototypeOnly: true,
  },
  {
    id: 'practice',
    path: '/app/practice',
    labelKey: 'nav.practice',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'primary',
    mobileNavigation: 'primary',
    requirementAreas: ['5.1', '5.2'],
    prototypeOnly: true,
  },
  {
    id: 'practice-session',
    path: '/app/practice/:sessionId',
    labelKey: 'nav.practiceSession',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['5.1', '5.2', '5.3'],
    prototypeOnly: true,
  },
  {
    id: 'practice-result',
    path: '/app/practice/:sessionId/result',
    labelKey: 'nav.practiceResult',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['5.3', '5.4'],
    prototypeOnly: true,
  },
  {
    id: 'practice-mistakes',
    path: '/app/practice/mistakes',
    labelKey: 'nav.mistakes',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['5.4'],
    prototypeOnly: true,
  },
  {
    id: 'practice-mistake-detail',
    path: '/app/practice/mistakes/:mistakeId',
    labelKey: 'nav.mistakeDetail',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['5.4', '6.4'],
    prototypeOnly: true,
  },
  {
    id: 'mock-exams',
    path: '/app/mock-exams',
    labelKey: 'nav.mockExams',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'primary',
    mobileNavigation: 'more',
    requirementAreas: ['7.1'],
    prototypeOnly: true,
  },
  {
    id: 'mock-instructions',
    path: '/app/mock-exams/:examId/instructions',
    labelKey: 'nav.mockInstructions',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['7.1', '7.2'],
    prototypeOnly: true,
  },
  {
    id: 'mock-session',
    path: '/app/mock-exams/:examId/session',
    labelKey: 'nav.mockSession',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['7.2', '7.3'],
    prototypeOnly: true,
  },
  {
    id: 'mock-result',
    path: '/app/mock-exams/:examId/result',
    labelKey: 'nav.mockResult',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    requirementAreas: ['7.4'],
    prototypeOnly: true,
  },
  {
    id: 'progress',
    path: '/app/progress',
    labelKey: 'nav.progress',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'primary',
    mobileNavigation: 'primary',
    requirementAreas: ['8.1', '8.3'],
    prototypeOnly: true,
  },
  {
    id: 'profile',
    path: '/app/profile',
    labelKey: 'nav.profile',
    availability: 'implemented',
    allowedRoles: STUDENT,
    navigation: 'primary',
    mobileNavigation: 'more',
    requirementAreas: ['1.3', '1.4'],
  },
  {
    id: 'profile-languages',
    path: '/app/profile/languages',
    labelKey: 'nav.languages',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'secondary',
    mobileNavigation: 'more',
    requirementAreas: ['1.4'],
    prototypeOnly: true,
  },
  {
    id: 'profile-family',
    path: '/app/profile/family',
    labelKey: 'nav.family',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'secondary',
    mobileNavigation: 'more',
    requirementAreas: ['2.2', '2.3'],
    prototypeOnly: true,
  },
  {
    id: 'profile-access',
    path: '/app/profile/access',
    labelKey: 'nav.access',
    availability: 'prototype',
    allowedRoles: STUDENT,
    navigation: 'secondary',
    mobileNavigation: 'more',
    requirementAreas: ['11.1', '11.2'],
    prototypeOnly: true,
  },
  {
    id: 'more',
    path: '/app/more',
    labelKey: 'nav.more',
    availability: 'implemented',
    allowedRoles: STUDENT,
    navigation: 'hidden',
    mobileNavigation: 'primary',
    requirementAreas: [],
  },
];

export const primaryNavRoutes = routeManifest.filter((r) => r.navigation === 'primary');
export const mobilePrimaryNavRoutes = routeManifest.filter(
  (route) => route.mobileNavigation === 'primary',
);
export const mobileMoreRoutes = routeManifest.filter((route) => route.mobileNavigation === 'more');

export function getRouteById(id: string): AppRouteDefinition | undefined {
  return routeManifest.find((r) => r.id === id);
}
