package com.yukcsca.identity.domain;

public enum SecurityEventType {
  GOOGLE_LOGIN_SUCCEEDED,
  GOOGLE_LOGIN_REJECTED,
  REFRESH_ROTATED,
  REFRESH_REJECTED,
  REFRESH_REUSE_DETECTED,
  LOGOUT,
  AUTH_RATE_LIMITED,
  CREDENTIAL_REGISTRATION_REQUESTED,
  CREDENTIAL_VERIFICATION_DELIVERY_SENT,
  CREDENTIAL_VERIFICATION_DELIVERY_FAILED,
  CREDENTIAL_VERIFICATION_SUCCEEDED,
  CREDENTIAL_VERIFICATION_REJECTED,
  CREDENTIAL_VERIFICATION_GOOGLE_COLLISION,
  CREDENTIAL_LOGIN_SUCCEEDED,
  CREDENTIAL_LOGIN_REJECTED,
  PASSWORD_RECOVERY_REQUESTED,
  PASSWORD_RECOVERY_DELIVERY_SENT,
  PASSWORD_RECOVERY_DELIVERY_FAILED,
  PASSWORD_RECOVERY_REJECTED,
  PASSWORD_RECOVERY_SUCCEEDED,
  STUDENT_ACTIVATION_SUCCEEDED,
  SESSION_CLEANUP
}
